services:
  - type: web
    name: predal-verifier
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 1 --timeout 300
    healthCheckPath: /healthz
    maxShutdownDelaySeconds: 300
    autoDeployTrigger: commit
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
